org: nivaldeir
app: serverless-test
service: serverless-test

plugins:

provider:
  name: aws
  runtime: nodejs18.x 
  stage: dev
  region: us-east-1
  environment:
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: '1'
    PORT: 3000
    NODE_OPTIONS: '--enable-source-maps --stack-trace-limit=1000'
functions:
  api:
    handler: src/index.handler
    events:
      - httpApi:
          path: /agenda
          method: get
      - httpApi:
          path: /agenda
          method: post
package:
  individually: true

custom:
  esbuild:
    bundle: true
    minify: false
    sourcemap: true
    target: 'node18'
    platform: 'node'
    concurrency: 10
